### ISSUE TITLE
MGC

### ISSUE THREAD

**Issue by malradhi** [naxingyu/MGCVocoder#1]
How does it work?

**Comment by naxingyu** [comment]
Usage is in the code.

**Comment by malradhi** [comment]
I know it was there, but does not work. Could you please check the configure file.

**Comment by naxingyu** [comment]
Does not work how? Which step did it fail? I cannot help if you do not provide the details.

**Comment by malradhi** [comment]
How can I provide details, if your "configure file" doesn't compile correctly. Anyhow, good luck and I'll close this comment !
